version: '3'
services:
  web:
    image: nginx
    tty: true
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - app
    ports:
      - 80:80
  app:
    build: ./docker/app
    tty: true
    volumes:
      - ./:/var/www
    working_dir: /var/www
